module.exports = {

    // Authentication
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    UNAUTHORIZED: "UNAUTHORIZED",

    // Portfolio
    EMPTY_PORTFOLIO: "EMPTY_PORTFOLIO",
    HOLDING_NOT_FOUND: "HOLDING_NOT_FOUND",

    // AI
    AI_ANALYSIS_FAILED: "AI_ANALYSIS_FAILED",
    AI_RESPONSE_INVALID: "AI_RESPONSE_INVALID",

    // Market
    MARKET_API_ERROR: "MARKET_API_ERROR",
    MARKET_API_TIMEOUT: "MARKET_API_TIMEOUT",

    // Generic
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
};