function Summary({ summary }) {

    return (

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-6 lg:p-8 shadow-lg hover:border-slate-700 transition-all duration-300">

            <div className="flex items-center gap-3 mb-6">

                <div className="text-4xl">

                    🤖

                </div>

                <div>

                    <h2 className="text-xl sm:text-2xl lg:text-3xl font-bold text-white">

                        CapitalMind Analysis

                    </h2>

                    <p className="text-slate-400 text-sm mt-1">

                        Generated by the CapitalMind AI Engine

                    </p>

                </div>

            </div>

            <div className="bg-slate-800/50 rounded-xl p-5 sm:p-6 border border-slate-700">

                <p className="text-slate-300 text-base sm:text-lg leading-7 sm:leading-8 text-justify">

                    {summary}

                </p>

            </div>

        </div>

    );

}

export default Summary;