function PortfolioAIInsights({ analysis }) {

    return (

        <div className="rounded-3xl border border-slate-800 bg-slate-900 p-8 shadow-xl">

            {/* Header */}

            <div className="mb-8">

                <h2 className="text-3xl font-black text-white">

                    🤖 AI Portfolio Review

                </h2>

                <p className="mt-2 text-slate-400">

                    Generated by the CapitalMind AI Portfolio Advisor

                </p>

            </div>

            {/* Top Metrics */}

            <div className="grid gap-6 md:grid-cols-3">

                <div className="rounded-2xl border border-slate-800 bg-slate-950 p-6">

                    <p className="text-sm text-slate-500">

                        Portfolio Score

                    </p>

                    <h3 className="mt-3 text-4xl font-black text-blue-400">

                        {analysis.portfolioScore}/100

                    </h3>

                </div>

                <div className="rounded-2xl border border-slate-800 bg-slate-950 p-6">

                    <p className="text-sm text-slate-500">

                        Risk Level

                    </p>

                    <h3 className="mt-3 text-4xl font-black text-yellow-400">

                        {analysis.riskLevel}

                    </h3>

                </div>

                <div className="rounded-2xl border border-slate-800 bg-slate-950 p-6">

                    <p className="text-sm text-slate-500">

                        Diversification

                    </p>

                    <h3 className="mt-3 text-4xl font-black text-green-400">

                        {analysis.diversificationScore}%

                    </h3>

                </div>

            </div>

            {/* Strengths & Weaknesses */}

            <div className="mt-8 grid gap-8 lg:grid-cols-2">

                <div className="rounded-2xl border border-green-700 bg-slate-950 p-6">

                    <h3 className="text-2xl font-bold text-green-400">

                        ✅ Strengths

                    </h3>

                    <ul className="mt-5 space-y-3">

                        {analysis.strengths.map((item, index) => (

                            <li
                                key={index}
                                className="flex gap-3 text-slate-300"
                            >

                                <span className="text-green-400">

                                    ✔

                                </span>

                                {item}

                            </li>

                        ))}

                    </ul>

                </div>

                <div className="rounded-2xl border border-red-700 bg-slate-950 p-6">

                    <h3 className="text-2xl font-bold text-red-400">

                        ❌ Weaknesses

                    </h3>

                    <ul className="mt-5 space-y-3">

                        {analysis.weaknesses.map((item, index) => (

                            <li
                                key={index}
                                className="flex gap-3 text-slate-300"
                            >

                                <span className="text-red-400">

                                    ✖

                                </span>

                                {item}

                            </li>

                        ))}

                    </ul>

                </div>

            </div>

            {/* Recommendations */}

            <div className="mt-8 rounded-2xl border border-blue-700 bg-slate-950 p-6">

                <h3 className="text-2xl font-bold text-blue-400">

                    📈 Recommendations

                </h3>

                <ul className="mt-5 space-y-3">

                    {analysis.recommendations.map((item, index) => (

                        <li
                            key={index}
                            className="flex gap-3 text-slate-300"
                        >

                            <span className="text-blue-400">

                                ➜

                            </span>

                            {item}

                        </li>

                    ))}

                </ul>

            </div>

        </div>

    );

}

export default PortfolioAIInsights;